<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>TotemStorageBag</AssemblyName>
    <RootNamespace>TotemStorageBag</RootNamespace>

    <!-- 把 NuGet 包 DLL（0Harmony）复制到输出目录，随 Mod 部署 -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <!-- 鸭科夫安装路径（包含 Duckov.exe 的目录），用于引用游戏 DLL -->
    <DuckovPath>E:\steam\steamapps\common\Escape from Duckov</DuckovPath>
    <SubPath>\Duckov_Data\Managed\</SubPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(DuckovPath)$(SubPath)TeamSoda.*">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)$(SubPath)ItemStatsSystem.dll">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)$(SubPath)SodaLocalization.dll">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)$(SubPath)UniTask.dll">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(DuckovPath)$(SubPath)Unity*">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
